image: ruby:2.6
deploy_develop:
  stage: deploy
  before_script:
    - apt-get update -qq
    - apt-get install -qq git dos2unix
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY_DEV >> ~/.ssh/$RSA64
    - cat ~/.ssh/$RSA64 |base64 -d > ~/.ssh/$RSA
    - chmod 400 ~/.ssh/$RSA
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - which ssh-agent
  script:
   - ssh -i ~/.ssh/$RSA -p $PUERTO_DEV $USUARIO_DEV@$IP_REMOTE_DEV "cd $DOCU_ROOT/$SITE_DEV/ && sudo git checkout $CI_COMMIT_REF_NAME && sudo git stash && sudo git pull origin $CI_COMMIT_REF_NAME && exit"
   #- ssh -i ~/.ssh/$RSA -p $PUERTO_DEV $USUARIO_DEV@$IP_REMOTE_DEV "cd $DOCU_ROOT/$SITE_DEV/ && sudo aws s3 cp s3://infra.uhomie.cl/dev3/env_dev3 $DOCU_ROOT/$SITE_DEVA/.env && exit"
  only:
   - develop
